version: '3'
services:
  
  mysql:
    image: mysql:latest
    container_name: nft-marathon-mysql-p2
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

  yourls:
    image: yourls:latest
    container_name: nft-marathon-yourls-p2
    restart: always
    ports:
      - '8080:80'
    environment:
      YOURLS_SITE: 'http://localhost:8080'
      YOURLS_DB_TYPE: mysql
      YOURLS_DB_USER: ${MYSQL_USER}
      YOURLS_DB_PASS: ${MYSQL_PASSWORD}
      YOURLS_DB_NAME: ${MYSQL_DATABASE}
      YOURLS_DB_HOST: mysql
      YOURLS_DB_PORT: 3306
      YOURLS_USER: yourls_admin_user
      YOURLS_PASS: yourls_admin_password
    volumes:
      - ./yourls-data:/var/www/html/user
    depends_on:
      - mysql
